## Import neccessary libraries

In [1]:
import pandas as pd
import numpy as np
import re

from pymongo import MongoClient

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Abdo
[nltk_data]     Hafez\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to C:\Users\Abdo
[nltk_data]     Hafez\AppData\Roaming\nltk_data...

True

## Connect to Atlas

In [2]:

MONGO_URI = "mongodb+srv://abdohafez731_db_user:xQ4Nmj6FoicluMap@cluster0.p6b5wtu.mongodb.net/"

client = MongoClient(MONGO_URI)

db = client["amazon_reviews_db"]

reviews_collection = db["reviews"]

d:\Programs\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:348: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

In [ ]:
# test connction
print(db.list_collection_names())

['users', 'products', 'reviews']

## Load Reviews from MongoDB

In [5]:
reviews_cursor = reviews_collection.find(
    {},
    {
        "reviewText": 1,
        "summary": 1,
        "overall": 1,
        "_id": 0
    }
)

reviews_list = list(reviews_cursor)

df = pd.DataFrame(reviews_list)

df.head()

,overall,reviewText,summary
0,5.0,Not much here to talk about other than it was ...,It Works
1,5.0,LIMITED SPACE ON YOUR DESK OR COMPUTER DESK OR...,WORK'S EXCELLENT!
2,5.0,works great,Five Stars
3,5.0,Worth every penny!! Durable light weight but y...,Excellent
4,5.0,the standard of 2 USB ports for computers isn'...,works great

## Create Sentiment Labels

In [6]:
def label_sentiment(rating):
    if rating >= 4:
        return "positive"
    elif rating == 3:
        return "neutral"
    else:
        return "negative"

df["sentiment"] = df["overall"].apply(label_sentiment)

## Combine Text Fields

In [7]:
df["text"] = (
    df["summary"].fillna('') + " " +
    df["reviewText"].fillna('')
)

## Text Cleaning Function

In [ ]:
stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()


def clean_text(text):
    text = text.lower() # lowercasing

    text = re.sub(r"http\S+", "", text) # remove links

    text = re.sub(r"[^a-zA-Z\s]", "", text) # remove symbols snd numbers
    words = text.split()

    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

## Apply Cleaning

In [9]:
df["clean_text"] = df["text"].apply(clean_text)

df.head()

,overall,reviewText,summary,sentiment,text,clean_text
0,5.0,Not much here to talk about other than it was ...,It Works,positive,It Works Not much here to talk about other tha...,work much talk exactly described worked right box
1,5.0,LIMITED SPACE ON YOUR DESK OR COMPUTER DESK OR...,WORK'S EXCELLENT!,positive,WORK'S EXCELLENT! LIMITED SPACE ON YOUR DESK O...,work excellent limited space desk computer des...
2,5.0,works great,Five Stars,positive,Five Stars works great,five star work great
3,5.0,Worth every penny!! Durable light weight but y...,Excellent,positive,Excellent Worth every penny!! Durable light we...,excellent worth every penny durable light weig...
4,5.0,the standard of 2 USB ports for computers isn'...,works great,positive,works great the standard of 2 USB ports for co...,work great standard usb port computer isnt rea...

## Remove Empty Rows

In [10]:
df = df[df["clean_text"].str.strip() != ""]

## Train/Test Split

In [11]:
X = df["clean_text"]

y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## Save Processed Dataset

In [12]:
df.to_csv(
    "../data/processed/sentiment_ready.csv",
    index=False
)